# MATH 210 Introduction to Mathematical Computing

**March 30, 2026**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Interpolation

Write a function called `interpolate` which takes sequences `x` and `y`, and returns a NumPy array of coefficients of the unique polynomial of degree $d$ which interpolates the data (where `d + 1 = len(x)`).

In [2]:
def interpolate(x,y):
    A = np.vander(x,increasing=True)
    c = la.solve(A,y)
    return c

In [3]:
x = [-1,0,1]
y = [0,1,0]
c = interpolate(x,y)
print(c,[1.,0.,-1.])

[ 1.  0. -1.] [1.0, 0.0, -1.0]


In [4]:
x = [0,1,2,3]
y = [0,0,0,1]
c = interpolate(x,y) # p(x) = (1/6)x(x - 1)(x - 2) = (1/6)x^3 - (1/2)x^2 + (1/3)x
print(c,[0,1/3,-1/2,1/6])

[ 0.          0.33333333 -0.5         0.16666667] [0, 0.3333333333333333, -0.5, 0.16666666666666666]


## Critical Points

Write a function called `cpinterpolate` which take sequences `x` and `y`, and returns a NumPy array of coefficients of the unique polynomial $p(x)$ of degree $2n - 1$ which interpolates the data (where `n = len(x)`) and satsifies $p'(x_i) = 0$ for each $i=0,\dots,n-1$.

What is the system we are trying to solve given 2 points $(x_0,y_0),(x_1,y_1)$?

\begin{align*}
c_0 + c_1 x_0 + c_2 x_0^2 + c_3 x_0^3 &= y_0 \\
c_0 + c_1 x_1 + c_2 x_1^2 + c_3 x_1^3 &= y_1 \\
          c_1 + 2c_2 x_0 + 3c_3 x_0^2 &= 0 \\
          c_1 + 2c_2 x_1 + 3c_3 x_1^2 &= 0
\end{align*}

$$
A = \begin{bmatrix} 
1 & x_0 & x_0^2 & x_0^3 \\
1 & x_1 & x_1^2 & x_1^3 \\
0 & 1 & 2x_0 & 3x_0^2 \\
0 & 1 & 2x_1 & 3x_1^2
\end{bmatrix}
\hspace{10mm}
\mathbf{b} = \begin{bmatrix} y_0 \\ y_1 \\ 0 \\ 0 \end{bmatrix}
$$

In [5]:
def cpinterpolate(x,y):
    n = len(x)
    x = np.array(x)
    A1 = np.column_stack([x**k for k in range(2*n)])
    A2 = np.column_stack([np.zeros(n)] + [k*x**(k-1) for k in range(1,2*n)])
    A = np.vstack([A1,A2])
    b = np.hstack([y,np.zeros(n)])
    c = la.solve(A,b)
    return c

In [6]:
x = [0]
y = [1]
c = cpinterpolate(x,y)
print(c,[1.,0.])

[1. 0.] [1.0, 0.0]


In [7]:
x = [-1,1]
y = [-1,3]
c = cpinterpolate(x,y) # p(x) = 1 + 3x - x^3, p'(x) = 3 - 3x^2
print(c,[1.,3.,0.,-1.])

[ 1.  3. -0. -1.] [1.0, 3.0, 0.0, -1.0]
