# MATH 210 Introduction to Mathematical Computing

**April 10, 2026**

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
A = np.array([[1.,1.],[1.,-2.]])
print(A)

[[ 1.  1.]
 [ 1. -2.]]


In [3]:
D,P = la.eig(A)
print(D)
print(P)

[ 1.30277564+0.j -2.30277564+0.j]
[[ 0.95709203 -0.28978415]
 [ 0.28978415  0.95709203]]


In [4]:
x = np.array([[1.],[0.]])
for k in range(11):
    x = A@x
    #x = x/np.max(np.abs(x))
    x = x/la.norm(x)
print(x)

[[-0.28377193]
 [ 0.9588918 ]]


In [10]:
eval1 = np.sum(x*(A@x))/np.sum(x*x)

In [11]:
print(eval1)

-2.302633631054072
