# MATH 210 Introduction to Mathematical Computing

**March 23, 2026**

* NumPy arrays
* `scipy.linalg`
* Linear System

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## NumPy Arrays

We can create NumPy arrays using the function `np.array` and entering a list of lists of numbers:

In [2]:
A = np.array([[1.,2.],[3.,4.]])
print(A)

[[1. 2.]
 [3. 4.]]


In [3]:
M = np.array([[-2.,1.,0.],[1.,-2.,1.],[0.,1.,-2.]])
print(M)

[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]


Typing out the values is tedious. We can use functions to create arrays:

In [4]:
A = np.zeros((4,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
D = np.diag([1.,2.,3.,4.])
print(D)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [7]:
O = np.ones((3,2))
print(O)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
D1 = np.diag([1.,2.,3.],-1)
print(D1)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]]


In [17]:
N = 10
A = -2*np.eye(N) + np.diag(np.ones(N-1),1) + np.diag(np.ones(N-1),-1)
print(A)

[[-2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -2.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -2.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -2.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -2.]]


## scipy.linalg

There is `numpy.linalg` and `scipy.linalg`. They are similar but different. We will use `scipy.linalg`.

In [18]:
import scipy.linalg as la

Use the funciton `la.solve` to compute solutions of $A \mathbf{x} = \mathbf{b}$.

In [20]:
A = np.array([[-2.,1.,0.],[1.,-2.,1.],[0.,1.,-2.]])
b = np.array([[1.],[1.],[1.]])
print(A)
print(b)

[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]
[[1.]
 [1.]
 [1.]]


In [21]:
x = la.solve(A,b)

In [22]:
x

array([[-1.5],
       [-2. ],
       [-1.5]])